"""empty message

Revision ID: 263f6a301d2f
Revises: a96e5887bfe7
Create Date: 2021-07-15 20:59:27.129615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263f6a301d2f'
down_revision = 'a96e5887bfe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'achievement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement_projects')
    # ### end Alembic commands ###
