"""empty message

Revision ID: 3a7c9ec34323
Revises: f71598e390b3
Create Date: 2021-07-15 18:38:38.028093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7c9ec34323'
down_revision = 'f71598e390b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('show_on_front', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'show_on_front')
    # ### end Alembic commands ###
