"""empty message

Revision ID: 487205d573ea
Revises: 8ecc423f7ef8
Create Date: 2021-07-15 18:53:01.217274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487205d573ea'
down_revision = '8ecc423f7ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_tags', 'show_on_front')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tags', sa.Column('show_on_front', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
