"""empty message

Revision ID: 7f8e84557a57
Revises: 8377d07d625f
Create Date: 2021-07-15 17:18:20.751725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8e84557a57'
down_revision = '8377d07d625f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aboutmes')
    op.add_column('achievements', sa.Column('order', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('achievements', 'desc',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('achievements', 'end_date',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('achievements', 'icon',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('achievements', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('achievements', 'start_date',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('collabs', 'fname',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('collabs', 'lname',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('idx_17555_sqlite_autoindex_projects_1', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['title'])
    op.alter_column('tags', 'knowledge',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('idx_17561_sqlite_autoindex_tags_1', table_name='tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'salt',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('idx_17567_sqlite_autoindex_users_1', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('idx_17567_sqlite_autoindex_users_1', 'users', ['username'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'salt',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_index('idx_17561_sqlite_autoindex_tags_1', 'tags', ['name'], unique=True)
    op.alter_column('tags', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tags', 'knowledge',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('idx_17555_sqlite_autoindex_projects_1', 'projects', ['title'], unique=True)
    op.alter_column('projects', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('collabs', 'lname',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('collabs', 'fname',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('achievements', 'start_date',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('achievements', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('achievements', 'icon',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('achievements', 'end_date',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('achievements', 'desc',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('achievements', 'order')
    op.create_table('aboutmes',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quote', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='idx_17537_aboutmes_pkey')
    )
    # ### end Alembic commands ###
