"""empty message

Revision ID: 8377d07d625f
Revises: 0c34a25fdbbc
Create Date: 2021-07-15 00:14:51.571202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8377d07d625f'
down_revision = '0c34a25fdbbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tags', sa.Column('show_on_front', sa.Boolean(), nullable=True))
    op.alter_column('projects', 'long_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'short_description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'short_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'long_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('project_tags', 'show_on_front')
    # ### end Alembic commands ###
