"""empty message

Revision ID: a96e5887bfe7
Revises: 487205d573ea
Create Date: 2021-07-15 18:54:27.566090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96e5887bfe7'
down_revision = '487205d573ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'desc',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'desc',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
