"""empty message

Revision ID: f71598e390b3
Revises: 7f8e84557a57
Create Date: 2021-07-15 18:37:51.282531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71598e390b3'
down_revision = '7f8e84557a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_tags', 'show_on_front')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tags', sa.Column('show_on_front', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
