apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mbresume
  name: resume
  labels:
    app: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: mbresume:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001