apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: NodePort
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001