apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: mbresume
spec:
  type: NodePort
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30001